### ISSUE TITLE
Remove this repo

### ISSUE THREAD

**Issue by ajm188** [cwruacm/scheduler#1]
Given that this fork has gotten to be 400+ commits behind its upstream, I feel this can clearly be deleted.

If hacsoc/ACM really still wants to maintain a fork of the project, we can fork it to the hacsoc org.

cc @thomasrussellmurphy

**Comment by thomasrussellmurphy** [comment]
And no development in either master since 2014/2013? Nuke, please.

**Comment by ajm188** [comment]
Going going gone.
